# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-19 02:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('abstract', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u6458\u8981')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='19/05/nv3.jpg', upload_to='article/%y/%m', verbose_name='\u6587\u7ae0\u5c01\u9762')),
                ('views_num', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('poll_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u70b9\u8d5e')),
                ('keep_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u6536\u85cf')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name': '\u6587\u7ae0\u7ba1\u7406',
                'verbose_name_plural': '\u6587\u7ae0\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('profile', models.CharField(default='', max_length=20, verbose_name='\u8d26\u53f7')),
                ('password', models.CharField(max_length=20, verbose_name='\u5bc6\u7801')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u4f5c\u8005\u4fe1\u606f',
                'verbose_name_plural': '\u4f5c\u8005\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='\u7c7b\u522b')),
                ('desc', models.TextField(verbose_name='\u8be6\u60c5')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u7c7b\u522b',
                'verbose_name_plural': '\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u6807\u7b7e')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.Category', verbose_name='\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
