# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-19 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleConment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('conment_time', models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('user', models.CharField(max_length=20, verbose_name='\u8bc4\u8bba\u8005')),
                ('poll_nums', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e')),
                ('comment_aticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='blog.Article', verbose_name='\u8bc4\u8bba\u6587\u7ae0')),
            ],
            options={
                'ordering': ['-conment_time'],
                'verbose_name': '\u6587\u7ae0\u8bc4\u8bba',
                'verbose_name_plural': '\u6587\u7ae0\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='ArticleConmentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('conment_time', models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('user', models.CharField(max_length=20, verbose_name='\u8bc4\u8bba\u8005')),
                ('poll_nums', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excomment', to='comment.ArticleConment', verbose_name='\u8bc4\u8bba\u4e00\u7ea7\u8bc4\u8bba')),
                ('reply', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='comment.ArticleConmentReply', verbose_name='\u7528\u6237\u95f4\u8bc4\u8bba')),
            ],
            options={
                'ordering': ['conment_time'],
                'verbose_name': '\u7528\u6237\u4e92\u8bc4',
                'verbose_name_plural': '\u7528\u6237\u4e92\u8bc4',
            },
        ),
    ]
